# =============================================================================
# USAGE  (project root entry point)
# =============================================================================
# Purpose:
#   Serves as the central graphical hub for the entire jet impingement
#   analysis pipeline. The interface presents a scrollable sidebar of tools
#   grouped into sections — a prominent global-pipeline launcher, a
#   collapsible Single-Case Pipeline section, and a Cross-Case Analysis
#   section — each launching the corresponding script in a new Tkinter window
#   with the global workspace folder automatically propagated. The main area
#   hosts an image gallery that discovers and displays all PNG figures
#   generated by the pipeline, organised by category (experiment subfolder,
#   thermal summaries, or cross-case summaries). The automated pipeline is
#   launched as a subprocess (pipeline.py) with parameters serialised to a
#   temporary JSON file. The Cross-Case Analysis section invokes the
#   superposition module to aggregate results across all experiment subfolders
#   and refresh the gallery. This script is the recommended entry point for
#   interactive use of the pipeline.
#
# Inputs:
#   - Global workspace folder selected by the user via the Browse button;
#     the folder must contain either an experiments/ subfolder with case
#     subfolders or be a direct case folder depending on the tool selected
#
# Outputs:
#   - No files are written by this script directly; it delegates all
#     computation and file I/O to the constituent processor and visualiser
#     scripts it launches
#
# Dependencies:
#   - All 12 processor and visualiser scripts (imported at startup):
#     thermal_processor, thermal_visualizer, Re_Ve_processor,
#     Re_comparison_processor, read_th_file_processor, mean_processor,
#     maps_2D_visualizer, graphs_1D_visualizer, frequency_processor,
#     frequency_visualizer, superposition
#   - pipeline.py (launched as a subprocess for the automated pipeline)
#
# Usage:
#   - python usage.py  (opens the Jet Impingement Analysis Hub GUI)
#   - This is the primary entry point for interactive analysis sessions
# =============================================================================

import sys
import tkinter as tk
from tkinter import messagebox, filedialog, ttk
import os
import glob
import time
import subprocess
import json
import re
import threading
import pandas as _pd

# --- PATH SETUP (root location) ---
_script_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(_script_dir, 'scripts', 'processors'))
sys.path.insert(0, os.path.join(_script_dir, 'scripts', 'visualizers'))
sys.path.insert(0, os.path.join(_script_dir, 'scripts', 'pipeline'))

# --- CONFIG LOADER ---
def _load_cfg(filename):
    filename = filename.replace('.csv', '.xlsx')
    _p = os.path.join(_script_dir, 'config', filename)
    _df = _pd.read_excel(_p, index_col='parameter')
    return _df['value'] if 'value' in _df.columns else _df.iloc[:, 0]

try:
    _cfg_geom = _load_cfg('config_geometry.csv')
except Exception:
    _cfg_geom = None

# Attempt to load Image library for the Gallery
try:
    from PIL import Image, ImageTk
    Image.MAX_IMAGE_PIXELS = None
    PIL_AVAILABLE = True
except ImportError:
    PIL_AVAILABLE = False

try:
    from thermal_processor import ThermalProcessorApp
    from thermal_visualizer import ThermalVisualizerApp, save_all_thermal_figures
    from Re_Ve_processor import ReVeCalculatorApp
    from Re_comparison_processor import ReComparisonApp
    from read_th_file_processor import CobraDataProcessorApp
    from mean_processor import DataMeansApp
    from maps_2D_visualizer import DataVisualizerApp, save_vertical_slice_profiles  # noqa: F401
    from graphs_1D_visualizer import Profile1DApp
    from frequency_processor import FrequencyProcessorApp
    from frequency_visualizer import FrequencyVisualizerApp
    from superposition import generate_superposition
    from data_intake import DataIntakeApp
    import pec_processor
    MODULES_LOADED = True
except ImportError as e:
    print(f"CRITICAL ERROR: Failed to load required modules.\nDetails: {e}\nEnsure all required .py files are present in the directory.")
    MODULES_LOADED = False


class MainWelcomeApp:
    def __init__(self, root):
        self.root = root
        self.root.title("Jet Impingement Analysis Hub")
        self.root.geometry("1100x800")

        # --- State Variables ---
        self.global_folder = tk.StringVar()
        self.use_global_folder = tk.BooleanVar(value=True)

        # Local working folder: after picking the global workspace once, the
        # user selects which case to work on from a dropdown (no re-browsing).
        # The sentinel below means "stay in the global folder" — used for
        # cross-case / global results.
        self.GLOBAL_OPTION = "(Global — all cases)"
        self.local_folder = tk.StringVar(value=self.GLOBAL_OPTION)

        # --- Persistent Pipeline Parameters (loaded from config where appropriate) ---
        _step_x  = str(float(_cfg_geom['grid_step_x']))          if _cfg_geom is not None else "5.0"
        _step_y  = str(float(_cfg_geom['grid_step_y']))          if _cfg_geom is not None else "1.5875"
        _x_start = str(float(_cfg_geom['x_start_offset']))       if _cfg_geom is not None else "38.0"
        _B_mm    = str(float(_cfg_geom['nozzle_height_B']))      if _cfg_geom is not None else "30.0"
        _d_cyl   = str(float(_cfg_geom['cylinder_diameter_D2'])) if _cfg_geom is not None else "12.0"
        _w_noz   = str(float(_cfg_geom['nozzle_width_cyl']))     if _cfg_geom is not None else "156.0"
        _d1      = str(float(_cfg_geom['tunnel_diameter_D1']))   if _cfg_geom is not None else "200.0"

        self.pipe_step_x  = tk.StringVar(value=_step_x)
        self.pipe_step_y  = tk.StringVar(value=_step_y)
        self.pipe_x_start = tk.StringVar(value=_x_start)
        self.pipe_y_start = tk.StringVar(value="0.0")
        self.pipe_az      = tk.StringVar(value="0.0")
        self.pipe_el      = tk.StringVar(value="0.0")
        self.pipe_roll    = tk.StringVar(value="0.0")
        self.pipe_B_mm    = tk.StringVar(value=_B_mm)
        self.pipe_d_cyl   = tk.StringVar(value=_d_cyl)
        self.pipe_w_noz   = tk.StringVar(value=_w_noz)
        self.pipe_d1      = tk.StringVar(value=_d1)
        self.pipe_dp      = tk.StringVar(value="10.0")

        self.gallery_images = []
        self.current_img_obj = None

        self._single_case_collapsed = tk.BooleanVar(value=True)

        # --- Gallery filter state ---
        self.gallery_cross_subcat = tk.StringVar(value="All")
        self.gallery_cross_slice  = tk.StringVar(value="All")
        self.gallery_case_type    = tk.StringVar(value="All")
        self.gallery_case_slice   = tk.StringVar(value="All")

        self.setup_ui()

    # ==========================================
    # FOLDER HELPERS
    # ==========================================
    def select_global_folder(self):
        folder = filedialog.askdirectory(title="Select Global Workspace Folder")
        if folder:
            self.global_folder.set(folder)
            self._populate_local_folders()
            self.refresh_gallery_categories()

    def _list_case_folders(self):
        """Return sorted case-folder names inside the global workspace.

        Cases live under experiments/ in the current layout; the old flat
        layout keeps them at the workspace root. Non-case helper folders are
        excluded in both cases."""
        root = self.global_folder.get()
        if not root or not os.path.isdir(root):
            return []
        _exclude = {'summary', 'thermal', 'experiments', 'scripts',
                    'config', 'new_data', '__pycache__'}
        exp = os.path.join(root, "experiments")
        scan_dir = exp if os.path.isdir(exp) else root
        try:
            return sorted(
                f.name for f in os.scandir(scan_dir)
                if f.is_dir() and f.name.lower() not in _exclude
            )
        except Exception:
            return []

    def _populate_local_folders(self):
        """Refresh the local-folder dropdown from the current global workspace."""
        cases = self._list_case_folders()
        values = [self.GLOBAL_OPTION] + cases
        if hasattr(self, 'combo_local'):
            self.combo_local['values'] = values
        # Reset selection to the global sentinel if the previous pick vanished.
        if self.local_folder.get() not in values:
            self.local_folder.set(self.GLOBAL_OPTION)

    def get_target_folder(self):
        """Folder for SINGLE-CASE tools.

        Returns the selected local case folder, or the global workspace when
        the user has chosen to stay in the global folder (the GLOBAL_OPTION
        sentinel)."""
        root = self.global_folder.get()
        if not root:
            return None
        sel = self.local_folder.get()
        if sel and sel != self.GLOBAL_OPTION:
            exp = os.path.join(root, "experiments")
            base = exp if os.path.isdir(exp) else root
            candidate = os.path.join(base, sel)
            if os.path.isdir(candidate):
                return candidate
        return root

    # The gallery view follows the same selection as the tools: the chosen
    # local case folder, or the global workspace when staying global.
    get_view_folder = get_target_folder

    def _on_local_folder_changed(self, event=None):
        """Switch the gallery to the selected local folder.

        Selecting a case shows that case's figures (single-case view); the
        '(Global — all cases)' sentinel returns to the cross-case / global
        view — mirroring what happens when the global workspace is (re)browsed.
        After picking the global workspace once, this dropdown is the only
        control needed to move between cases."""
        self.refresh_gallery_categories()

    # ==========================================
    # LOG HELPER
    # ==========================================
    def log_msg(self, msg):
        print(msg)  # fallback to console (runs in background thread)

    # ==========================================
    # SINGLE-CASE PIPELINE DIALOG
    # ==========================================
    def open_pipeline_dialog(self):
        folder = self.get_target_folder()
        if not folder or not os.path.exists(folder):
            messagebox.showwarning("Input Needed", "Please select a valid Global Workspace first.")
            return

        dialog = tk.Toplevel(self.root)
        dialog.title("Pipeline Configuration")
        dialog.geometry("520x750")
        dialog.transient(self.root)
        dialog.grab_set()

        tk.Label(dialog, text="Pre-Flight Settings", font=("Arial", 16, "bold"), bg="#004e92", fg="white", pady=10).pack(fill="x")
        tk.Label(dialog, text="Verify the experimental parameters below before\nlaunching the 7-step automated pipeline.", pady=10).pack()

        form_frame = tk.Frame(dialog, padx=20, pady=10)
        form_frame.pack(fill="both", expand=True)

        def add_row(parent, label_text, string_var, row_idx):
            tk.Label(parent, text=label_text, font=("Arial", 10, "bold")).grid(row=row_idx, column=0, sticky="e", pady=5, padx=10)
            tk.Entry(parent, textvariable=string_var, width=15).grid(row=row_idx, column=1, sticky="w")

        tk.Label(form_frame, text="Grid & Offset Parameters", font=("Arial", 10, "italic"), fg="#555").grid(row=0, column=0, columnspan=2, sticky="w", pady=(0, 5))
        add_row(form_frame, "Step X (mm):", self.pipe_step_x, 1)
        add_row(form_frame, "Step Y (mm):", self.pipe_step_y, 2)
        add_row(form_frame, "X Start Offset (mm):", self.pipe_x_start, 3)
        add_row(form_frame, "Y Manual Offset (mm):", self.pipe_y_start, 4)

        tk.Label(form_frame, text="Probe Rotations (Degrees)", font=("Arial", 10, "italic"), fg="#555").grid(row=5, column=0, columnspan=2, sticky="w", pady=(15, 5))
        add_row(form_frame, "Azimuth:", self.pipe_az, 6)
        add_row(form_frame, "Elevation:", self.pipe_el, 7)
        add_row(form_frame, "Roll:", self.pipe_roll, 8)

        tk.Label(form_frame, text="Physical Geometry", font=("Arial", 10, "italic"), fg="#555").grid(row=9, column=0, columnspan=2, sticky="w", pady=(15, 5))
        add_row(form_frame, "Nozzle B (mm):", self.pipe_B_mm, 10)
        add_row(form_frame, "Nozzle Width (mm):", self.pipe_w_noz, 11)
        add_row(form_frame, "Cylinder Diameter 'D' (mm):", self.pipe_d_cyl, 12)
        add_row(form_frame, "Tunnel D1 (mm):", self.pipe_d1, 13)

        tk.Label(form_frame, text="Environment Variables", font=("Arial", 10, "italic"), fg="#555").grid(row=14, column=0, columnspan=2, sticky="w", pady=(15, 5))
        add_row(form_frame, "Delta P Tunnel (Pa):", self.pipe_dp, 15)

        def start_pipeline():
            try:
                params = {
                    'step_x': float(self.pipe_step_x.get()),
                    'step_y': float(self.pipe_step_y.get()),
                    'x_start': float(self.pipe_x_start.get()),
                    'y_start': float(self.pipe_y_start.get()),
                    'az': float(self.pipe_az.get()),
                    'el': float(self.pipe_el.get()),
                    'roll': float(self.pipe_roll.get()),
                    'B_mm': float(self.pipe_B_mm.get()),
                    'd_cyl': float(self.pipe_d_cyl.get()),
                    'w_noz': float(self.pipe_w_noz.get()),
                    'd1': float(self.pipe_d1.get()),
                    'dp': float(self.pipe_dp.get())
                }
                if params['B_mm'] <= 0:
                    raise ValueError("Nozzle height B must be > 0.")
            except ValueError:
                messagebox.showerror("Format Error", "All parameters must be valid numbers.", parent=dialog)
                return

            dialog.destroy()

            config_path = os.path.join(folder, "temp_pipeline_config.json")
            with open(config_path, 'w') as f:
                json.dump(params, f)

            try:
                pipeline_path = os.path.join(_script_dir, 'scripts', 'pipeline', 'pipeline.py')
                subprocess.Popen([sys.executable, pipeline_path, "--folder", folder, "--config", config_path])
                messagebox.showinfo("Pipeline Launched", "The automated pipeline has been launched in the background.\nYou can continue using the dashboard while it calculates.")
            except Exception as e:
                messagebox.showerror("Execution Error", f"Failed to start pipeline: {e}")

        btn_frame = tk.Frame(dialog, pady=15)
        btn_frame.pack(fill="x")

        tk.Button(btn_frame, text="Cancel", command=dialog.destroy, width=10).pack(side="left", padx=20)
        tk.Button(btn_frame, text="✓ Data is correct, proceed to pipeline", command=start_pipeline,
                  bg="#28a745", fg="white", font=("Arial", 11, "bold")).pack(side="right", padx=20)

    # ==========================================
    # FULL ANALYSIS PIPELINE — ALL CASES
    # ==========================================
    def run_full_analysis_pipeline(self):
        """Run the full pipeline for ALL cases in experiments/, then run cross-case analysis."""
        parent_dir = self.global_folder.get()
        if not parent_dir or not os.path.exists(parent_dir):
            messagebox.showwarning("Input Needed", "Please select a valid Global Workspace first.")
            return

        experiments_dir = os.path.join(parent_dir, "experiments")
        if not os.path.isdir(experiments_dir):
            messagebox.showerror("Error", f"No experiments/ folder found in:\n{parent_dir}")
            return

        # First: process any new data in new_data/
        new_data_dir = os.path.join(parent_dir, "new_data")
        if os.path.isdir(new_data_dir):
            new_cases = [f.path for f in os.scandir(new_data_dir) if f.is_dir()]
            if new_cases:
                try:
                    from data_intake import register_case
                    for case_path in new_cases:
                        try:
                            success, msg = register_case(
                                os.path.basename(case_path), new_data_dir, experiments_dir,
                                os.path.join(parent_dir, 'config', 'config_cases.xlsx')
                            )
                            self.log_msg(f"Intake: {msg}")
                        except Exception as e:
                            self.log_msg(f"Intake error: {e}")
                except ImportError as e:
                    self.log_msg(f"data_intake not available: {e}")

        # Then: run single-case pipeline for each case
        cases = sorted([f.path for f in os.scandir(experiments_dir) if f.is_dir()])
        if not cases:
            messagebox.showinfo("Info", "No cases found in experiments/")
            return

        pipeline_path = os.path.join(_script_dir, 'scripts', 'pipeline', 'pipeline.py')

        # Build config from config CSV files — no dependency on GUI fields
        def _g(key, fallback):
            try: return float(_cfg_geom[key]) if _cfg_geom is not None else fallback
            except Exception: return fallback
        config_data = {
            'B_mm':   _g('nozzle_height_B', 30.0),
            'step_x': _g('grid_step_x', 5.0),
            'step_y': _g('grid_step_y', 1.5875),
            'x_start': _g('x_start_offset', 38.0),
            'y_start': 0.0, 'az': 0.0, 'el': 0.0, 'roll': 0.0,
            'd_cyl': _g('cylinder_diameter_D2', 12.0),
            'w_noz': _g('nozzle_width_cyl', 156.0),
            'd1':    _g('tunnel_diameter_D1', 200.0),
            'dp': 0.0,
        }
        config_file_path = os.path.join(_script_dir, 'config', '_pipeline_run_config.json')
        with open(config_file_path, 'w') as _f:
            json.dump(config_data, _f)

        def _run_sequentially():
            for i, case_path in enumerate(cases, 1):
                case_name = os.path.basename(case_path)
                self.log_msg(f"[{i}/{len(cases)}] Starting pipeline for: {case_name}")
                p = subprocess.Popen(
                    [sys.executable, pipeline_path, "--folder", case_path, "--config", config_file_path]
                )
                p.wait()  # wait for this case to finish before starting the next
                self.log_msg(f"[{i}/{len(cases)}] Finished: {case_name}")

            # All cases done — run cross-case superposition
            try:
                generate_superposition(parent_dir)
                self.root.after(0, lambda: messagebox.showinfo(
                    "Done",
                    f"Full analysis pipeline complete!\n{len(cases)} case(s) processed sequentially.\nSuperposition generated."
                ))
                self.root.after(0, self.refresh_gallery_categories)
            except Exception as e:
                self.root.after(0, lambda: messagebox.showerror("Error", f"Superposition failed:\n{e}"))

        threading.Thread(target=_run_sequentially, daemon=True).start()
        messagebox.showinfo(
            "Running",
            f"Full pipeline started — processing {len(cases)} case(s) one at a time.\n"
            "Progress is printed to the console. The GUI stays responsive."
        )

    # ==========================================
    # THERMAL ANALYSIS PIPELINE
    # ==========================================
    def run_thermal_pipeline(self):
        """Single-button thermal analysis: compute → save figures → refresh gallery."""
        folder = self.global_folder.get()
        if not folder or not os.path.exists(folder):
            messagebox.showwarning("Input Needed", "Please select a valid Global Workspace first.")
            return

        def _run():
            # Step 1 — run thermal_processor headlessly in a withdrawn Tk window
            _root = tk.Tk()
            _root.withdraw()
            try:
                app = ThermalProcessorApp(_root, default_folder=folder)
                app.run_master_pipeline(folder)   # synchronous call — we are already in a background thread
            except Exception as e:
                self.root.after(0, lambda err=str(e): messagebox.showerror(
                    "Thermal Processing Error", f"Processing failed:\n{err}"
                ))
                return
            finally:
                try: _root.destroy()
                except Exception: pass

            # Step 2 — save all figures headlessly
            _, msg = save_all_thermal_figures(folder)

            # Step 3 — refresh gallery and notify
            self.root.after(0, self.refresh_gallery_categories)
            self.root.after(0, lambda m=msg: messagebox.showinfo(
                "Thermal Analysis Complete",
                f"Processing and figures complete.\n{m}"
            ))

        threading.Thread(target=_run, daemon=True).start()
        messagebox.showinfo(
            "Thermal Analysis Running",
            "Thermal processing started in background.\n"
            "The gallery will update automatically when done."
        )

    # ==========================================
    # RUN SUPERPOSITION SCRIPT
    # ==========================================
    def run_superposition_tool(self):
        # Cross-case analysis always operates on the GLOBAL workspace, regardless
        # of the local case selection.
        folder = self.global_folder.get()
        if not folder or not os.path.exists(folder):
            messagebox.showwarning("Input Needed", "Please select a valid Parent Global Workspace containing the experiment subfolders.")
            return

        try:
            generate_superposition(folder)
            messagebox.showinfo("Success", "Superposition Summary complete!\n\nThe gallery has been updated with the new summary charts.")
            self.refresh_gallery_categories()
        except Exception as e:
            messagebox.showerror("Error", f"Failed to generate superposition:\n{e}")

    # ==========================================
    # CATEGORY-SPECIFIC SUPERPOSITION RUNNERS
    # ==========================================
    def _run_category(self, func, label):
        """Generic wrapper: validate folder, call func in thread, refresh gallery.

        Category superposition is cross-case, so it always uses the GLOBAL
        workspace folder (not the local case selection)."""
        folder = self.global_folder.get()
        if not folder or not os.path.exists(folder):
            messagebox.showwarning("Input Needed",
                                   "Please select a valid Global Workspace first.")
            return

        def _run():
            try:
                func(folder)
                self.root.after(0, lambda: messagebox.showinfo(
                    "Done", f"{label} figures regenerated."))
                self.root.after(0, self.refresh_gallery_categories)
            except Exception as e:
                self.root.after(0, lambda err=str(e): messagebox.showerror(
                    "Error", f"{label} failed:\n{err}"))

        threading.Thread(target=_run, daemon=True).start()

    def run_superposition_velocity(self):
        from superposition import generate_velocity_plots
        self._run_category(generate_velocity_plots, "Velocity")

    def run_superposition_decay(self):
        from superposition import generate_decay_plot
        self._run_category(generate_decay_plot, "Plane Jet Decay")

    def run_superposition_psds(self):
        from superposition import generate_psd_plots
        self._run_category(generate_psd_plots, "PSDs")

    def run_superposition_turbulence(self):
        from superposition import generate_turbulence_plots
        self._run_category(generate_turbulence_plots, "Turbulence Intensity")

    # ==========================================
    # THERMAL-HYDRAULIC PEC (pumping penalty)
    # ==========================================
    def run_pec_tool(self):
        """Compute the Webb PEC (Nu/Nu0)/(f/f0)^(1/3) from the pumping-penalty
        workbook + the thermal summary, show the per-Re table, and refresh the
        gallery (the PEC_vs_Re figure is written into summary/)."""
        def _run():
            try:
                _curves, pec = pec_processor.run()
                cols = ['Setpoint_Pa', 'Re', 'Nu_over_Nu0', 'f_over_f0',
                        'ff0_pow_1_3', 'PEC', 'u_PEC_pct']
                hdr = f"{'Pa':>3} {'Re':>8} {'Nu/Nu0':>7} {'f/f0':>6} {'(f/f0)^1/3':>11} {'PEC':>6} {'u_PEC%':>7}"
                lines = [hdr, "-" * len(hdr)]
                for _, r in pec[cols].iterrows():
                    lines.append(f"{int(r['Setpoint_Pa']):>3} {r['Re']:>8.0f} "
                                 f"{r['Nu_over_Nu0']:>7.3f} {r['f_over_f0']:>6.2f} "
                                 f"{r['ff0_pow_1_3']:>11.3f} {r['PEC']:>6.3f} "
                                 f"{r['u_PEC_pct']:>6.1f}%")
                lo, hi = pec['PEC'].min(), pec['PEC'].max()
                lines += ["", f"PEC range: {lo:.3f}-{hi:.3f}  (>1 = net benefit at constant pumping power)",
                          "Figure 'PEC_vs_Re' written to summary/ and pumping_penalty/."]
                self.root.after(0, lambda t="\n".join(lines): self._show_pec_window(t))
                self.root.after(0, self.refresh_gallery_categories)
            except Exception as e:
                self.root.after(0, lambda err=str(e): messagebox.showerror(
                    "PEC failed", f"Could not compute PEC:\n{err}"))

        threading.Thread(target=_run, daemon=True).start()

    def _show_pec_window(self, text):
        win = tk.Toplevel(self.root)
        win.title("Thermal-Hydraulic Performance (PEC)")
        win.geometry("620x320")
        txt = tk.Text(win, font=("Consolas", 10), wrap="none", bg="#fbfbfb")
        txt.insert("1.0", text)
        txt.config(state="disabled")
        txt.pack(fill="both", expand=True, padx=8, pady=8)
        tk.Button(win, text="Close", command=win.destroy).pack(pady=4)

    # ==========================================
    # IMAGE GALLERY DICTIONARY & LOGIC
    # ==========================================
    def get_pretty_name(self, filename):
        base = os.path.splitext(filename)[0]
        # Cross-case station profiles (X/B sweep) — uniform label for all stations.
        for _stn, _pretty in (("NearNozzle", "Near-nozzle"), ("MidField", "Mid-field"),
                              ("NearPlate", "Near-plate")):
            if base.startswith(f"Superposed_{_stn}_"):
                _rest = (base.replace(f"Superposed_{_stn}_", "")
                         .replace("_over_Umax", "/Umax").replace("_", " "))
                return f"{_pretty} {_rest} (X/B sweep)"
        mapping = {
            "Velocity_Vector_Map": "Velocity Vector Map",
            "Flow_Streamlines": "Flow Streamlines",
            "Vorticity_Field": "2D Vorticity Field (ωz)",
            "Turbulence_Intensity_Map": "Turbulence Intensity Field",
            "Static_Pressure_Map": "Static Pressure Field",
            "Superposed_1st_Dominant_Freq": "Superposed 1st Dominant Freq",
            "All_Centerline_PSDs_Grid": "All Centerline PSDs Mega-Grid",
            # Cross-case velocity centerline (the NearNozzle/MidField/NearPlate
            # station sweeps are auto-labelled by the transform above).
            "Superposed_Vmag_Centerline":           "Superposed Velocity Magnitude — Centerline",
            # Thermal visualizer outputs
            "Qloss_vs_dT_Fit": "Thermal Loss Ratio vs ΔT",
            "Global_Nu_vs_Re": "Global Nusselt Number vs Reynolds",
            "Spatial_Nusselt_Maps": "Local Nusselt Number Mapping",
            "Spatial_DeltaT_Maps": "Local ΔT Mapping",
            # Transverse spatial profile plots (Pla cases)
            "Transverse_U_over_Umax":    "Transverse Profiles — U/Umax",
            "Transverse_V_over_Umax":    "Transverse Profiles — V/Umax",
            "Transverse_W_over_Umax":    "Transverse Profiles — W/Umax",
            "Transverse_Vmag_over_Umax": "Transverse Profiles — Vmag/Umax",
            "Transverse_I_u_Pct":        "Transverse Profiles — Iu [%]",
            "Transverse_I_v_Pct":        "Transverse Profiles — Iv [%]",
            "Transverse_I_w_Pct":        "Transverse Profiles — Iw [%]",
            "Transverse_I_uvw_Pct":      "Transverse Profiles — Iuvw [%]",
        }
        if base in mapping:
            return mapping[base]
        if base.startswith("Profile_"):
            return base.replace("Profile_", "1D Profile: ").replace("_", " ")
        if base.endswith("_PSD"):
            return f"PSD (FFT) - {base.replace('_PSD', '')}"
        return base.replace("_", " ")

    def _get_relevant_pngs(self, folder):
        """Helper logic to detect parent folders and specific subfolders like thermal."""
        summary_dir = os.path.join(folder, "summary")
        temp_dir = os.path.join(folder, "thermal")
        pump_dir = os.path.join(folder, "pumping_penalty")
        experiments_dir = os.path.join(folder, "experiments")
        is_parent = False

        try:
            # Check experiments/ subfolder for experiment case folders
            if os.path.isdir(experiments_dir):
                for item in os.listdir(experiments_dir):
                    full_path = os.path.join(experiments_dir, item)
                    if os.path.isdir(full_path):
                        if os.path.exists(os.path.join(full_path, "Processed_CSVs")) or \
                           os.path.exists(os.path.join(full_path, "2D_Profiles_Results")):
                            is_parent = True
                            break
            # Fallback: check root-level folders (old structure)
            if not is_parent:
                for item in os.listdir(folder):
                    if item in ["summary", "thermal", "experiments", "scripts", "__pycache__"]:
                        continue
                    full_path = os.path.join(folder, item)
                    if os.path.isdir(full_path):
                        if os.path.exists(os.path.join(full_path, "Processed_CSVs")) or \
                           os.path.exists(os.path.join(full_path, "2D_Profiles_Results")):
                            is_parent = True
                            break
        except Exception:
            pass

        files = []
        if is_parent:
            # Grab Aerodynamic Summaries
            if os.path.exists(summary_dir):
                files.extend(glob.glob(os.path.join(summary_dir, "**", "*.png"), recursive=True))
            # Grab Thermal Summaries from thermal folder
            if os.path.exists(temp_dir):
                files.extend(glob.glob(os.path.join(temp_dir, "**", "*.png"), recursive=True))
            # Grab Pumping-Penalty / PEC figures
            if os.path.exists(pump_dir):
                files.extend(glob.glob(os.path.join(pump_dir, "*.png")))
        else:
            files = glob.glob(os.path.join(folder, "**", "*.png"), recursive=True)

        return [f for f in files if "__pycache__" not in f]

    def _get_category_for_file(self, filepath):
        """Intelligently assigns a clean category name based on the file's path."""
        parts = filepath.split(os.sep)
        if "pumping_penalty" in parts:
            return "Pumping Penalty / PEC"
        if "thermal" in parts:
            return "Thermal Summaries"
        elif "summary" in parts:
            return "Cross-Case Summaries"
        else:
            parent_dir = os.path.basename(os.path.dirname(filepath))
            grandparent_dir = os.path.basename(os.path.dirname(os.path.dirname(filepath)))
            return f"{grandparent_dir} / {parent_dir}" if parent_dir == "PNG" else parent_dir

    def refresh_gallery_categories(self):
        folder = self.get_view_folder()
        if not folder or not os.path.exists(folder):
            return

        png_files = self._get_relevant_pngs(folder)

        categories = set()
        for f in png_files:
            categories.add(self._get_category_for_file(f))

        cats = sorted(list(categories))
        if cats:
            self.combo_category['values'] = cats
            self.combo_category.current(0)
            self._reset_subfilters()
            self._update_filter_visibility()
            self.load_gallery_images()
        else:
            self.combo_category['values'] = ["No images found"]
            self.combo_category.current(0)
            self._update_filter_visibility()
            self.combo_image['values'] = [""]
            self.combo_image.set("")
            self.gallery_images = []
            self.display_selected_image()

    def _reset_subfilters(self):
        """Reset all sub-filter combos to 'All' and clear dynamic value lists."""
        self.gallery_cross_subcat.set("All")
        self.gallery_cross_slice.set("All")
        self.gallery_case_type.set("All")
        self.gallery_case_slice.set("All")
        # Reset option lists so stale values from the previous category are not
        # visible in the dropdown while the new category's images are loading.
        self.combo_case_type['values'] = ["All"]
        self.combo_case_slice['values'] = ["All"]

    # ------------------------------------------------------------------
    # DATA-AWARE OPTION HELPERS
    # ------------------------------------------------------------------

    def _present_types(self, files):
        """Return sorted list of Type labels actually represented in *files*."""
        seen = set()
        for f in files:
            seen.add(self._case_type_for_file(os.path.basename(f)))
        return sorted(seen)

    def _present_slices(self, files):
        """Return sorted list of Slice display labels actually represented in *files*.

        Only the two recognised orientations are checked; files that match
        neither are silently omitted (they will still appear under 'All').
        """
        seen = set()
        for f in files:
            bn = os.path.basename(f)
            if "_Y_" in bn:
                seen.add("Horizontal (Y/B=0)")
            if "_X_" in bn or "XB" in bn:
                seen.add("Vertical (X/B=const)")
        return sorted(seen)

    def _on_subfilter_changed(self, event=None):
        """Called when any sub-filter combobox selection changes."""
        self._apply_gallery_filters()

    def load_gallery_images(self, event=None):
        """Load images for the selected category, then reset sub-filters and apply them."""
        folder = self.get_view_folder()
        target_cat = self.combo_category.get()
        if not folder or target_cat == "No images found":
            return

        # Reset sub-filters and update which rows are visible whenever category changes
        self._reset_subfilters()
        self._update_filter_visibility()

        all_pngs = self._get_relevant_pngs(folder)
        # Build full list for this category (unfiltered)
        self._gallery_images_unfiltered = [
            f for f in all_pngs if self._get_category_for_file(f) == target_cat
        ]
        self._gallery_images_unfiltered.sort()

        self._apply_gallery_filters()

    def _apply_gallery_filters(self, event=None):
        """Re-filter _gallery_images_unfiltered using active sub-filter selections.

        For single-case categories this also:
          - Repopulates the Type combobox with only the types present in the
            current image set; resets to 'All' if the prior selection vanished.
          - After applying the Type filter, repopulates the Slice combobox with
            only the slice orientations present among the type-filtered files;
            resets to 'All' if the prior selection vanished.
          - Hides the Slice row entirely when fewer than two slice orientations
            exist (it would add no useful discrimination).
        """
        if not hasattr(self, '_gallery_images_unfiltered'):
            return

        files = list(self._gallery_images_unfiltered)
        cat = self.combo_category.get()

        if self._is_cross_case_category(cat):
            files = self._filter_by_cross_subcat(files, self.gallery_cross_subcat.get())
            files = self._filter_by_cross_slice(files, self.gallery_cross_slice.get())

        elif self._is_single_case_category(cat):
            # --- Step 1: repopulate Type combo from the full unfiltered set ---
            present_types = self._present_types(files)
            type_options = ["All"] + present_types
            self.combo_case_type['values'] = type_options
            if self.gallery_case_type.get() not in type_options:
                self.gallery_case_type.set("All")

            # --- Step 2: apply Type filter ---
            files = self._filter_by_case_type(files, self.gallery_case_type.get())

            # --- Step 3: repopulate Slice combo from the type-filtered set ---
            present_slices = self._present_slices(files)
            slice_options = ["All"] + present_slices
            self.combo_case_slice['values'] = slice_options
            if self.gallery_case_slice.get() not in slice_options:
                self.gallery_case_slice.set("All")

            # Hide Slice row when there is at most one distinct orientation
            # (nothing useful to filter on); show it otherwise.
            if len(present_slices) < 2:
                self.row_case_slice.pack_forget()
            else:
                # Re-pack only if the type row is already visible (safety guard)
                if self.row_case_type.winfo_ismapped():
                    self.row_case_slice.pack(fill="x", pady=2)

            # --- Step 4: apply Slice filter ---
            slice_val = self.gallery_case_slice.get()
            if "Horizontal" in slice_val:
                slice_key = "Horizontal"
            elif "Vertical" in slice_val:
                slice_key = "Vertical"
            else:
                slice_key = "All"
            files = self._filter_by_case_slice(files, slice_key)

        self.gallery_images = files
        pretty_names = [self.get_pretty_name(os.path.basename(f)) for f in self.gallery_images]
        self.combo_image['values'] = pretty_names

        if pretty_names:
            self.combo_image.current(0)
            self.display_selected_image()
        else:
            self.combo_image.set("")
            self.lbl_image.config(image='', text="No images match the selected filters.")

    # ------------------------------------------------------------------
    # CROSS-CASE SUBCATEGORY HELPERS
    # ------------------------------------------------------------------

    # Keywords that map a filename to a Cross-Case subcategory.
    _CROSS_SUBCAT_KEYWORDS = {
        "Velocity":             ["U_Normalized", "V_Centerline", "W_Centerline", "Vmag",
                                 "over_Umax"],   # covers NearNozzle/MidField/NearPlate U/V/W/Vmag
        "Turbulence Intensity": ["I_u", "I_v", "I_w", "I_uvw"],
        "Plane Jet Decay":      ["Plane_Jet_Decay"],
        "Frequency":            ["Freq", "Dominant", "PSD", "Strouhal", "Centerline_St", "Cascade"],
    }

    def _cross_subcat_for_file(self, filename):
        """Return the Cross-Case subcategory name for *filename* (basename)."""
        for subcat, keywords in self._CROSS_SUBCAT_KEYWORDS.items():
            for kw in keywords:
                if kw in filename:
                    return subcat
        return "Other"

    def _filter_by_cross_subcat(self, files, subcat):
        """Return the subset of *files* that belong to *subcat* ('All' returns all)."""
        if subcat == "All":
            return files
        return [f for f in files if self._cross_subcat_for_file(os.path.basename(f)) == subcat]

    def _filter_by_cross_slice(self, files, slice_sel):
        """Filter cross-case superposed figures by profile slice.

        Station figures carry 'NearNozzle' / 'MidField' / 'NearPlate' in their
        filename (X/B sweep at the first / middle / last station); everything else
        in the Cross-Case set is a centerline / global summary. ('All' returns all.)"""
        if slice_sel == "All":
            return files
        _markers = {"Near-nozzle": "NearNozzle", "Mid-field": "MidField",
                    "Near-plate": "NearPlate"}
        out = []
        for f in files:
            base = os.path.basename(f)
            is_station = any(m in base for m in _markers.values())
            if slice_sel in _markers:
                if _markers[slice_sel] in base:
                    out.append(f)
            elif slice_sel == "Centerline" and not is_station:
                out.append(f)
        return out

    # ------------------------------------------------------------------
    # SINGLE-CASE TWO-LEVEL FILTER HELPERS
    # ------------------------------------------------------------------

    _CASE_TYPE_KEYWORDS = {
        "Velocity":             ["U_over", "V_over", "W_over", "Vmag", "U_max", "Velocity"],
        "Turbulence Intensity": ["I_u", "I_v", "I_w", "I_uvw", "Turbulence"],
        "Frequency":            ["PSD", "FFT", "Freq", "Strouhal", "Centerline_St",
                                 "Coherence", "Cascade"],
        "2D Profiles":          ["Transverse", "Butterfly", "VSlice"],
    }

    def _case_type_for_file(self, filename):
        """Return the single-case Type for *filename*."""
        for type_name, keywords in self._CASE_TYPE_KEYWORDS.items():
            for kw in keywords:
                if kw in filename:
                    return type_name
        return "Miscellaneous"

    def _filter_by_case_type(self, files, type_sel):
        """Filter *files* by the selected Type ('All' returns all)."""
        if type_sel == "All":
            return files
        return [f for f in files if self._case_type_for_file(os.path.basename(f)) == type_sel]

    def _filter_by_case_slice(self, files, slice_sel):
        """Filter *files* by slice orientation ('All', 'Horizontal', 'Vertical')."""
        if slice_sel == "All":
            return files
        result = []
        for f in files:
            bn = os.path.basename(f)
            if slice_sel == "Horizontal" and "_Y_" in bn:
                result.append(f)
            elif slice_sel == "Vertical" and ("_X_" in bn or "XB" in bn):
                result.append(f)
        return result

    # ------------------------------------------------------------------
    # UI HELPERS — show/hide the extra filter rows
    # ------------------------------------------------------------------

    def _is_cross_case_category(self, cat):
        return cat == "Cross-Case Summaries"

    def _is_single_case_category(self, cat):
        """True when the selected category is a single experiment case (not summary/thermal)."""
        return cat not in ("Cross-Case Summaries", "Thermal Summaries",
                           "Pumping Penalty / PEC", "No images found", "")

    def _update_filter_visibility(self):
        """Show/hide the extra filter rows depending on the selected category.

        For single-case categories only the Type row is shown here; the Slice
        row visibility is handled dynamically inside _apply_gallery_filters
        (shown only when ≥2 slice orientations are present in the current set).
        """
        cat = self.combo_category.get()
        if self._is_cross_case_category(cat):
            self.row_cross_subcat.pack(fill="x", pady=2)
            self.row_cross_slice.pack(fill="x", pady=2)
            self.row_case_type.pack_forget()
            self.row_case_slice.pack_forget()
        elif self._is_single_case_category(cat):
            self.row_cross_subcat.pack_forget()
            self.row_cross_slice.pack_forget()
            self.row_case_type.pack(fill="x", pady=2)
            # row_case_slice will be shown/hidden by _apply_gallery_filters
            # after it has computed which slices are actually present.
        else:
            self.row_cross_subcat.pack_forget()
            self.row_cross_slice.pack_forget()
            self.row_case_type.pack_forget()
            self.row_case_slice.pack_forget()

    # ------------------------------------------------------------------
    # IMAGE DISPLAY
    # ------------------------------------------------------------------

    def display_selected_image(self, event=None):
        if not PIL_AVAILABLE:
            self.lbl_image.config(text="Pillow library required for image viewer.\nPlease run: pip install Pillow")
            return

        idx = self.combo_image.current()
        if idx < 0 or not self.gallery_images:
            self.lbl_image.config(image='', text="No image selected or found in this directory.")
            return

        img_path = self.gallery_images[idx]

        try:
            img = Image.open(img_path)
            img.thumbnail((750, 600), Image.Resampling.LANCZOS)
            self.current_img_obj = ImageTk.PhotoImage(img)
            self.lbl_image.config(image=self.current_img_obj, text="")
        except Exception as e:
            self.lbl_image.config(image='', text=f"Error loading image:\n{e}")

    # ==========================================
    # UI SETUP & TOOL LAUNCHERS
    # ==========================================
    def setup_ui(self):
        header = tk.Label(self.root, text="Jet Impingement Hub", font=("Arial", 22, "bold"),
                          bg="#004e92", fg="white", pady=15)
        header.pack(fill="x")

        self.main_content = tk.Frame(self.root, bg="white", relief="sunken", bd=2)
        self.main_content.pack(side="left", fill="both", expand=True, padx=10, pady=10)

        gal_top = tk.Frame(self.main_content, bg="#f4f4f4", pady=10)
        gal_top.pack(fill="x")

        row1 = tk.Frame(gal_top, bg="#f4f4f4")
        row1.pack(fill="x", pady=2)
        tk.Label(row1, text="1. Select Category:", font=("Arial", 11, "bold"), bg="#f4f4f4",
                 width=18, anchor="e").pack(side="left", padx=5)
        self.combo_category = ttk.Combobox(row1, state="readonly", width=40)
        self.combo_category.pack(side="left", padx=5)
        self.combo_category.bind('<<ComboboxSelected>>', self.load_gallery_images)
        tk.Button(row1, text="↻ Refresh Scans", command=self.refresh_gallery_categories,
                  bg="#17a2b8", fg="white").pack(side="left", padx=10)

        # --- Row 1b: Cross-Case subcategory (shown only for Cross-Case Summaries) ---
        self.row_cross_subcat = tk.Frame(gal_top, bg="#f4f4f4")
        # (not packed here — visibility controlled by _update_filter_visibility)
        tk.Label(self.row_cross_subcat, text="  Subcategory:", font=("Arial", 10, "italic"),
                 bg="#f4f4f4", width=18, anchor="e").pack(side="left", padx=5)
        self.combo_cross_subcat = ttk.Combobox(
            self.row_cross_subcat, state="readonly", width=30,
            textvariable=self.gallery_cross_subcat,
            values=["All", "Velocity", "Turbulence Intensity",
                    "Plane Jet Decay", "Frequency"])
        self.combo_cross_subcat.pack(side="left", padx=5)
        self.combo_cross_subcat.bind('<<ComboboxSelected>>', self._on_subfilter_changed)

        # --- Row 1b2: Cross-Case slice (Centerline vs Near-plate) ---
        self.row_cross_slice = tk.Frame(gal_top, bg="#f4f4f4")
        # (not packed here — visibility controlled by _update_filter_visibility)
        tk.Label(self.row_cross_slice, text="  Slice:", font=("Arial", 10, "italic"),
                 bg="#f4f4f4", width=18, anchor="e").pack(side="left", padx=5)
        self.combo_cross_slice = ttk.Combobox(
            self.row_cross_slice, state="readonly", width=30,
            textvariable=self.gallery_cross_slice,
            values=["All", "Centerline", "Near-nozzle", "Mid-field", "Near-plate"])
        self.combo_cross_slice.pack(side="left", padx=5)
        self.combo_cross_slice.bind('<<ComboboxSelected>>', self._on_subfilter_changed)

        # --- Row 1c: Single-case Type filter ---
        self.row_case_type = tk.Frame(gal_top, bg="#f4f4f4")
        # (not packed here)
        tk.Label(self.row_case_type, text="  Type:", font=("Arial", 10, "italic"),
                 bg="#f4f4f4", width=18, anchor="e").pack(side="left", padx=5)
        self.combo_case_type = ttk.Combobox(
            self.row_case_type, state="readonly", width=30,
            textvariable=self.gallery_case_type,
            values=["All", "Velocity", "Turbulence Intensity",
                    "Frequency", "2D Profiles", "Miscellaneous"])
        self.combo_case_type.pack(side="left", padx=5)
        self.combo_case_type.bind('<<ComboboxSelected>>', self._on_subfilter_changed)

        # --- Row 1d: Single-case Slice filter ---
        self.row_case_slice = tk.Frame(gal_top, bg="#f4f4f4")
        # (not packed here)
        tk.Label(self.row_case_slice, text="  Slice:", font=("Arial", 10, "italic"),
                 bg="#f4f4f4", width=18, anchor="e").pack(side="left", padx=5)
        self.combo_case_slice = ttk.Combobox(
            self.row_case_slice, state="readonly", width=30,
            textvariable=self.gallery_case_slice,
            values=["All", "Horizontal (Y/B=0)", "Vertical (X/B=const)"])
        self.combo_case_slice.pack(side="left", padx=5)
        self.combo_case_slice.bind('<<ComboboxSelected>>', self._on_subfilter_changed)

        row2 = tk.Frame(gal_top, bg="#f4f4f4")
        row2.pack(fill="x", pady=2)
        tk.Label(row2, text="2. Select Figure:", font=("Arial", 11, "bold"), bg="#f4f4f4",
                 width=18, anchor="e").pack(side="left", padx=5)
        self.combo_image = ttk.Combobox(row2, state="readonly", width=55)
        self.combo_image.pack(side="left", padx=5)
        self.combo_image.bind('<<ComboboxSelected>>', self.display_selected_image)

        self.lbl_image = tk.Label(self.main_content, bg="white",
                                  text="[ Select a Workspace to load the Image Gallery ]",
                                  font=("Arial", 12, "italic"), fg="#888")
        self.lbl_image.pack(expand=True, fill="both", padx=10, pady=10)

        # -------------------------------------------------------------
        # SCROLLABLE SIDEBAR SETUP
        # -------------------------------------------------------------
        self.sidebar_container = tk.Frame(self.root, width=320, relief="raised", bd=2)
        self.sidebar_container.pack(side="right", fill="y", padx=10, pady=10)
        self.sidebar_container.pack_propagate(False)

        self.sidebar_canvas = tk.Canvas(self.sidebar_container, bg="#e0e0e0", highlightthickness=0)
        self.sidebar_scrollbar = ttk.Scrollbar(self.sidebar_container, orient="vertical",
                                               command=self.sidebar_canvas.yview)

        self.sidebar = tk.Frame(self.sidebar_canvas, bg="#e0e0e0")

        self.sidebar_canvas.configure(yscrollcommand=self.sidebar_scrollbar.set)

        self.sidebar_scrollbar.pack(side="right", fill="y")
        self.sidebar_canvas.pack(side="left", fill="both", expand=True)

        self.canvas_window = self.sidebar_canvas.create_window((0, 0), window=self.sidebar, anchor="nw")

        self.sidebar.bind("<Configure>",
                          lambda e: self.sidebar_canvas.configure(scrollregion=self.sidebar_canvas.bbox("all")))
        self.sidebar_canvas.bind("<Configure>",
                                 lambda e: self.sidebar_canvas.itemconfig(self.canvas_window, width=e.width))

        # Bind Mouse Wheel for scrolling
        self.sidebar_canvas.bind_all("<MouseWheel>", self._on_mousewheel)

        # -------------------------------------------------------------
        # POPULATING THE SIDEBAR
        # -------------------------------------------------------------

        # 1. Global Workspace selector
        g_frame = tk.LabelFrame(self.sidebar, text=" 1. Global Workspace ", bg="#e0e0e0",
                                font=("Arial", 10, "bold"), pady=5)
        g_frame.pack(fill="x", padx=10, pady=10)
        tk.Entry(g_frame, textvariable=self.global_folder, state="readonly").pack(fill="x", padx=5, pady=2)
        tk.Button(g_frame, text="Browse...", command=self.select_global_folder).pack(fill="x", padx=5, pady=2)

        # Local working-folder selector — pick the case to work on without
        # re-browsing. "(Global — all cases)" stays in the global workspace.
        tk.Label(g_frame, text="Working (local) folder:", bg="#e0e0e0",
                 font=("Arial", 8, "italic")).pack(anchor="w", padx=5, pady=(6, 0))
        self.combo_local = ttk.Combobox(g_frame, state="readonly",
                                        textvariable=self.local_folder,
                                        values=[self.GLOBAL_OPTION])
        self.combo_local.pack(fill="x", padx=5, pady=2)
        self.combo_local.bind('<<ComboboxSelected>>', self._on_local_folder_changed)
        tk.Label(g_frame,
                 text="Single-case tools use this folder.\nCross-case tools always use the global folder.",
                 bg="#e0e0e0", fg="#555", font=("Arial", 7), justify="left").pack(anchor="w", padx=5, pady=(0, 2))

        # --- BIG global pipeline buttons ---
        tk.Button(
            self.sidebar,
            text="🚀 Run Full Analysis — All Cases",
            command=self.run_full_analysis_pipeline,
            bg="#e67e00", fg="white",
            font=("Arial", 12, "bold"),
            pady=12
        ).pack(fill="x", padx=10, pady=(10, 3))

        tk.Button(
            self.sidebar,
            text="Run Thermal Analysis Pipeline",
            command=self.run_thermal_pipeline,
            bg="#c0392b", fg="white",
            font=("Arial", 10, "bold"),
            pady=7
        ).pack(fill="x", padx=10, pady=(3, 2))

        tk.Frame(self.sidebar, height=2, bg="#aaa").pack(fill="x", padx=5, pady=2)

        # -------------------------------------------------------------
        # COLLAPSIBLE SINGLE-CASE PIPELINE SECTION
        # -------------------------------------------------------------
        single_case_frame = tk.LabelFrame(
            self.sidebar,
            text=" Single-Case Pipeline (click to expand) ",
            bg="#e0e0e0",
            font=("Arial", 9, "italic")
        )
        single_case_frame.pack(fill="x", padx=10, pady=5)

        single_case_inner = tk.Frame(single_case_frame, bg="#e0e0e0")
        # starts collapsed — do NOT pack yet

        def toggle_single_case():
            if self._single_case_collapsed.get():
                # currently collapsed → expand
                single_case_inner.pack(fill="x")
                self._single_case_collapsed.set(False)
                toggle_btn.config(text="▲ Hide Single-Case Tools")
            else:
                # currently expanded → collapse
                single_case_inner.pack_forget()
                self._single_case_collapsed.set(True)
                toggle_btn.config(text="▼ Show Single-Case Tools")

        toggle_btn = tk.Button(
            single_case_frame,
            text="▼ Show Single-Case Tools",
            command=toggle_single_case,
            bg="#e0e0e0",
            relief="flat",
            font=("Arial", 8)
        )
        toggle_btn.pack(anchor="w", padx=5, pady=2)

        # RUN SINGLE-CASE PIPELINE button (inside collapsible)
        tk.Button(
            single_case_inner,
            text="🚀 RUN SINGLE-CASE PIPELINE",
            command=self.open_pipeline_dialog,
            bg="#ffc107", fg="black",
            font=("Arial", 11, "bold"),
            pady=8
        ).pack(fill="x", padx=8, pady=8)

        tk.Label(single_case_inner, text="2. Manual Processors", font=("Arial", 11, "bold"),
                 bg="#e0e0e0", pady=5).pack(fill="x")
        self._add_inner_btn(single_case_inner, "Re and Velocity Calculator", self.open_flow_calculator, "#28a745")
        self._add_inner_btn(single_case_inner, "Re & Velocity Comparison", self.open_re_comparison, "#20c997")
        self._add_inner_btn(single_case_inner, "Cobra Data Processor", self.open_cobra_processor, "#17a2b8")
        self._add_inner_btn(single_case_inner, "Spatial Map Averager", self.open_data_means, "#6f42c1")
        self._add_inner_btn(single_case_inner, "FFT & Aerodynamics Processor", self.open_freq_processor, "#e83e8c")
        self._add_inner_btn(single_case_inner, "Thermal & Power Processor", self.open_thermal_processor, "#ff8c00")

        tk.Frame(single_case_inner, height=2, bg="#ccc").pack(fill="x", pady=5)

        tk.Label(single_case_inner, text="3. Manual Visualizers", font=("Arial", 11, "bold"),
                 bg="#e0e0e0", pady=5).pack(fill="x")
        self._add_inner_btn(single_case_inner, "2D Flow Visualizer", self.open_visualizer, "#007acc")
        self._add_inner_btn(single_case_inner, "Vertical Slice Profiles", self.run_vertical_slice_profiles, "#0069d9")
        self._add_inner_btn(single_case_inner, "1D Profiles Viewer", self.open_1d_profiles, "#d9534f")
        self._add_inner_btn(single_case_inner, "Time & Frequency Visualizer", self.open_freq_visualizer, "#343a40")
        self._add_inner_btn(single_case_inner, "Thermal Results Visualizer", self.open_thermal_visualizer, "#ff5722")

        tk.Frame(self.sidebar, height=2, bg="#ccc").pack(fill="x", pady=5)

        # -------------------------------------------------------------
        # 4. CROSS-CASE ANALYSIS
        # -------------------------------------------------------------
        tk.Label(self.sidebar, text="4. Cross-Case Analysis", font=("Arial", 11, "bold"),
                 bg="#e0e0e0", pady=5).pack(fill="x")
        self.add_tool_button("Generate Aerodynamic Summary", self.run_superposition_tool, "#85144b")

        # Category buttons — regenerate only a subset of figures
        tk.Label(self.sidebar, text="  or regenerate by category:",
                 font=("Arial", 8, "italic"), bg="#e0e0e0").pack(anchor="w", padx=12)
        _cat_frame = tk.Frame(self.sidebar, bg="#e0e0e0")
        _cat_frame.pack(fill="x", padx=10, pady=(0, 4))

        _cat_buttons = [
            ("Velocity",            self.run_superposition_velocity,    "#6a0572"),
            ("Plane Jet Decay",     self.run_superposition_decay,       "#7b2d8b"),
            ("PSDs",                self.run_superposition_psds,        "#8c4aa3"),
            ("Turbulence Intensity",self.run_superposition_turbulence,  "#9d68bb"),
        ]
        for _col, (_txt, _cmd, _clr) in enumerate(_cat_buttons):
            # 2-column grid of small buttons
            _row_i = _col // 2
            _col_i = _col % 2
            tk.Button(_cat_frame, text=_txt, command=_cmd,
                      bg=_clr, fg="white",
                      font=("Arial", 8, "bold"), pady=4,
                      wraplength=110).grid(row=_row_i, column=_col_i,
                                           sticky="ew", padx=3, pady=2)
        _cat_frame.columnconfigure(0, weight=1)
        _cat_frame.columnconfigure(1, weight=1)

        self.add_tool_button("Thermal–Hydraulic PEC (pumping penalty)", self.run_pec_tool, "#2a8c9e")

        self.add_tool_button("Import New Case Data", self.open_data_intake, "#6f42c1")

    # ==========================================
    # MOUSE WHEEL
    # ==========================================
    def _on_mousewheel(self, event):
        try:
            widget_under_mouse = self.root.winfo_containing(event.x_root, event.y_root)
        except KeyError:
            return
        if widget_under_mouse and str(widget_under_mouse).startswith(str(self.sidebar_container)):
            self.sidebar_canvas.yview_scroll(int(-1 * (event.delta / 120)), "units")

    # ==========================================
    # BUTTON HELPERS
    # ==========================================
    def add_tool_button(self, text, command, color):
        """Add a button to the main sidebar."""
        btn = tk.Button(self.sidebar, text=text, command=command, bg=color, fg="white",
                        font=("Arial", 10, "bold"), pady=5)
        btn.pack(fill="x", padx=10, pady=3)

    def _add_inner_btn(self, parent, text, command, color):
        """Add a button inside the collapsible single-case frame."""
        btn = tk.Button(parent, text=text, command=command, bg=color, fg="white",
                        font=("Arial", 10, "bold"), pady=5)
        btn.pack(fill="x", padx=8, pady=3)

    # ==========================================
    # TOOL LAUNCHERS
    # ==========================================
    def launch_tool(self, app_class, name):
        if not MODULES_LOADED or app_class.__name__ not in globals():
            messagebox.showerror("Dependency Error", f"Module missing: {name}")
            return
        try:
            new_window = tk.Toplevel(self.root)
            app_class(new_window, default_folder=self.get_target_folder())
        except Exception as e:
            messagebox.showerror("Execution Error", f"Error:\n{e}")

    def open_flow_calculator(self):    self.launch_tool(ReVeCalculatorApp,       "Re_Ve_Calculator.py")
    def open_re_comparison(self):      self.launch_tool(ReComparisonApp,          "Re_comparison_processor.py")
    def open_cobra_processor(self):    self.launch_tool(CobraDataProcessorApp,    "read_th_file_processor.py")
    def open_data_means(self):         self.launch_tool(DataMeansApp,             "mean_processor.py")
    def open_visualizer(self):         self.launch_tool(DataVisualizerApp,        "maps_2D_visualizer.py")

    def run_vertical_slice_profiles(self):
        folder = self.get_target_folder()
        if not folder or not os.path.exists(folder):
            messagebox.showwarning("Input Needed", "Please select a valid case folder first.")
            return
        def _run():
            try:
                save_vertical_slice_profiles(folder)
                self.root.after(0, self.refresh_gallery_categories)
                self.root.after(0, lambda: messagebox.showinfo(
                    "Done", "Vertical slice profiles saved to 2D_Profiles_Results/PNG/"))
            except Exception as e:
                self.root.after(0, lambda: messagebox.showerror("Error", str(e)))
        threading.Thread(target=_run, daemon=True).start()

    def open_1d_profiles(self):        self.launch_tool(Profile1DApp,             "graphs_1D_visualizer.py")
    def open_freq_processor(self):     self.launch_tool(FrequencyProcessorApp,    "frequency_processor.py")
    def open_freq_visualizer(self):    self.launch_tool(FrequencyVisualizerApp,   "frequency_visualizer.py")
    def open_thermal_processor(self):  self.launch_tool(ThermalProcessorApp,      "thermal_processor.py")
    def open_thermal_visualizer(self): self.launch_tool(ThermalVisualizerApp,     "thermal_visualizer.py")

    def open_data_intake(self):
        try:
            new_window = tk.Toplevel(self.root)
            DataIntakeApp(new_window)
        except Exception as e:
            messagebox.showerror("Execution Error", f"Error launching Data Intake:\n{e}")


if __name__ == "__main__":
    root = tk.Tk()
    app = MainWelcomeApp(root)
    root.mainloop()
